In [40]:
	
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

In [41]:
data = pd.read_csv('/Users/sharvitkashikar/Training-june/day7/ecosystem_data.csv')
data

      water_quality  air_quality_index  ...   soil_ph  ecosystem_health
0         37.454012         112.092246  ...  5.144016          degraded
1         95.071431          99.873629  ...  4.021498          degraded
2         73.199394          52.846174  ...  4.194976          degraded
3         59.865848         182.180001  ...  4.493691          degraded
4         15.601864         142.987248  ...  4.620093          degraded
...             ...                ...  ...       ...               ...
9995      85.765599         263.111589  ...  6.923449          degraded
9996      89.750884          14.044187  ...  4.744065           at risk
9997      94.670792          91.109541  ...  7.619473          degraded
9998      39.748799         132.996002  ...  6.365560          degraded
9999      21.714040          51.679444  ...  8.239387          degraded

[10000 rows x 6 columns]

In [42]:
data['ecosystem_health'].unique()

array(['degraded', 'at risk', 'healthy'], dtype=object)

In [43]:
data['ecosystem_health'] = data['ecosystem_health'].map({'healthy': 1, 'at risk': 0, 'degraded': 2})
data

      water_quality  air_quality_index  ...   soil_ph  ecosystem_health
0         37.454012         112.092246  ...  5.144016                 2
1         95.071431          99.873629  ...  4.021498                 2
2         73.199394          52.846174  ...  4.194976                 2
3         59.865848         182.180001  ...  4.493691                 2
4         15.601864         142.987248  ...  4.620093                 2
...             ...                ...  ...       ...               ...
9995      85.765599         263.111589  ...  6.923449                 2
9996      89.750884          14.044187  ...  4.744065                 0
9997      94.670792          91.109541  ...  7.619473                 2
9998      39.748799         132.996002  ...  6.365560                 2
9999      21.714040          51.679444  ...  8.239387                 2

[10000 rows x 6 columns]

In [44]:
X = data[['water_quality','air_quality_index','biodiversity_index','vegetation_cover','soil_ph']]
y = data['ecosystem_health']
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [45]:
gnb = GaussianNB()
# Train the classifier
gnb.fit(X_train, y_train)
# Make predictions on the test set
y_pred = gnb.predict(X_test)
# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

Accuracy: 95.15%